### ISSUE TITLE
my spring schedule project use sofa and jarslink can start but uninstall failed

### ISSUE THREAD

**Issue by larrychao** [sofastack/sofa-boot#161]
我的项目是一个任务调度系统，希望引入sofa和jarslink，测试程序遇到了比较严重的问题，希望能帮我看看是什么原因，谢谢。

这个测试项目(Spring boot)代码引入了如下依赖：
`

        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-jarslink-ark-starter</artifactId>
            <classifier>ark-plugin</classifier>
            <version>2.0.0-SNAPSHOT</version>
        </dependency>

        
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>runtime-sofa-boot-starter</artifactId>
            <classifier>ark-plugin</classifier>
            <version>2.5.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>runtime-sofa-boot-starter</artifactId>
            <version>2.5.0-SNAPSHOT</version>
        </dependency>`

通过指令：java -jar target/app-one-1.0-SNAPSHOT-executable-ark.jar 可以启动这个项目
运行状态也在我的预期内 

通过 telnet localhost 1234
可以看到已经install的bizname
bizName='app-one', bizVersion='1.0-SNAPSHOT', bizState='activated'

执行Uninstall
uninstall -b -n app-one -v 1.0-SNAPSHOT

从控制台看到名为‘app-one’的biz执行了关闭，但不彻底，导致定时任务依然在执行，但zookeeper已经被关闭了，大概如下：

`INFO 15556 --- [ver-worker-0-T1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@22a71081: startup date [Tue Jul 31 17:33:14 CST 2018]; root of context hierarchy
2018-07-31 17:33:50.580  INFO 15556 --- [ver-worker-0-T1] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-07-31 17:33:51.085  INFO 15556 --- [tor-Framework-0] o.a.c.f.imps.CuratorFrameworkImpl        : backgroundOperationsLoop exiting
2018-07-31 17:33:51.093  INFO 15556 --- [ver-worker-0-T1] org.apache.zookeeper.ZooKeeper           : Session: 0x10008ad8a380055 closed
2018-07-31 17:33:51.099 ERROR 15556 --- [ain-EventThread] o.a.c.framework.recipes.cache.TreeCache  : 

java.lang.IllegalStateException: instance must be started before calling this method
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[guava-16.0.jar!/:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getChildren(CuratorFrameworkImpl.java:391) ~[curator-framework-2.10.0.jar!/:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.doRefreshChildren(TreeCache.java:263) ~[curator-recipes-2.10.0.jar!/:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.refreshChildren(TreeCache.java:251) ~[curator-recipes-2.10.0.jar!/:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.process(TreeCache.java:351) ~[curator-recipes-2.10.0.jar!/:na]
	at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:62) [curator-framework-2.10.0.jar!/:na]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522) [zookeeper-3.4.6.jar!/:na]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) [zookeeper-3.4.6.jar!/:na]

2018-07-31 17:33:51.100 ERROR 15556 --- [tor-TreeCache-0] o.a.c.framework.recipes.cache.TreeCache  : 

com.tigerbrokers.infra.schedule.reg.exception.RegException: java.lang.IllegalStateException: instance must be started before calling this method
	at com.tigerbrokers.infra.schedule.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:36) ~[tiger-schedule-core-1.0-SNAPSHOT.jar!/:na]
	at com.tigerbrokers.infra.schedule.reg.zookeeper.ZookeeperRegistryCenter.isExisted(ZookeeperRegistryCenter.java:189) ~[tiger-schedule-core-1.0-SNAPSHOT.jar!/:na]
	at com.tigerbrokers.infra.schedule.internal.storage.JobNodeStorage.isJobNodeExisted(JobNodeStorage.java:45) ~[tiger-schedule-core-1.0-SNAPSHOT.jar!/:na]
	at com.tigerbrokers.infra.schedule.internal.election.LeaderService.hasLeader(LeaderService.java:77) ~[tiger-schedule-core-1.0-SNAPSHOT.jar!/:na]
	at com.tigerbrokers.infra.schedule.internal.election.ElectionListenerManager$LeaderElectionJobListener.isActiveElection(ElectionListenerManager.java:55) ~[tiger-schedule-core-1.0-SNAPSHOT.jar!/:na]
	at com.tigerbrokers.infra.schedule.internal.election.ElectionListenerManager$LeaderElectionJobListener.dataChanged(ElectionListenerManager.java:49) ~[tiger-schedule-core-1.0-SNAPSHOT.jar!/:na]
	at com.tigerbrokers.infra.schedule.internal.listener.AbstractJobListener.childEvent(AbstractJobListener.java:28) ~[tiger-schedule-core-1.0-SNAPSHOT.jar!/:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:732) [curator-recipes-2.10.0.jar!/:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:726) [curator-recipes-2.10.0.jar!/:na]
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.10.0.jar!/:na]
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [guava-16.0.jar!/:na]
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [curator-framework-2.10.0.jar!/:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:725) [curator-recipes-2.10.0.jar!/:na]
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:71) [curator-recipes-2.10.0.jar!/:na]
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:843) [curator-recipes-2.10.0.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.lang.IllegalStateException: instance must be started before calling this method
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[guava-16.0.jar!/:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkExists(CuratorFrameworkImpl.java:367) ~[curator-framework-2.10.0.jar!/:na]
	at com.tigerbrokers.infra.schedule.reg.zookeeper.ZookeeperRegistryCenter.isExisted(ZookeeperRegistryCenter.java:186) ~[tiger-schedule-core-1.0-SNAPSHOT.jar!/:na]
	... 20 common frames omitted

2018-07-31 17:33:51.100 ERROR 15556 --- [ain-EventThread] o.a.c.framework.recipes.cache.TreeCache  : 
`

之后是一只重复这个状态，因为schedule仍在继续，因此出错
不知道你们有没有建议，我该怎样修改这个测试代码，谢谢！

**Comment by larrychao** [comment]
我这个测试代码，是在测试一个基于elastic-job的任务调度系统。
elastic-job的核心是，采用java中的quartz进行任务调度，但通过zookeeper取代quartz中原来的数据库从而提高性能。

**Comment by larrychao** [comment]
我的理解是,uninstall 时并没有将必须要的对象close

**Comment by larrychao** [comment]
@QilongZhang 这个scedule应该是有quartz起线程的，我研究一下

**Comment by ScienJus** [comment]
我之前好像遇到过类似的问题，elastic-job 如果在 spring 环境启动的话，可能没有绑定销毁时的生命周期，导致 spring 容器关闭时没办法关闭 quartz 线程。

你是使用的 SpringJobScheduler 这个类么？尝试在配置时额外写一个子类继承它，并在销毁的时候调用一下 `schedulerFacade#shutdown`。

详情可以参考下 https://github.com/elasticjob/elastic-job-lite/issues/525 这个 issue，希望能帮到你，验证的话可以通过 jstack 确认。

**Comment by larrychao** [comment]
@ScienJus 多谢啊，我确实用的SpringJobSchedule这个类，而且有派生这个类
我试试看

**Comment by larrychao** [comment]
@ScienJus 昨晚试了一下，增加对SpringJobSchedule，确切说是JobScheduler中的SchedulerFacade的释放，功能就正常了。而Elastic-job自身提供了ShutdownListenerManager，在应用shutdown的时候会释放JobScheduler的，不知道Jarslink在uninstall为什么没有触发shutdown @QilongZhang 。

**Comment by ScienJus** [comment]
@larrychao ShutdownListenerManager 是从 zookeeper 当中监听到了当前节点已被删除时，停掉自身的任务，和这个 case 似乎关联不大。elastic-job 似乎也没有关闭时先从 zookeeper 注销自己，然后还要等待监听器触发停止任务之后才关闭的逻辑（也许有只是我没看到）。

总之，这个问题感觉和 jarslink 关系不大，主要还是 elastic-job 本身没有绑定到 spring 的生命周期中，这个增强应该是完全无害的。
