### ISSUE TITLE
使用直连调用的地址使用https域名报Send message to remote catch error: HTTP 302 Found

### ISSUE THREAD

**Issue by mailfly** [sofastack/sofa-boot#474]
使用直连调用：
    @SofaReference(jvmFirst = false, binding = @SofaReferenceBinding(bindingType = "rest",directUrl = "https://www.xxx.com"))
    private SimpleApi simpleApi ;
调用的时候报如下错误：
	2019-08-30 18:00:04,820 [SOFA-SEV-REST-BIZ-8888-6-T1] INFO  com.alipay.sofa.common.log- Connect to com.demo.simple.sofa.SimpleApi  provider:https://www.baidu.com success ! The connection is www.baidu.com:80 <-> 172.20.19.82:0
2019-08-30 18:00:04,932 [SOFA-SEV-REST-BIZ-8888-6-T1] ERROR c.p.f.microservice.starter.sofa.resteasy.exception.SofaRpcExceptionMapper- Unhandled SofaRpcException: com.alipay.sofa.rpc.core.exception.SofaRpcException
com.alipay.sofa.rpc.core.exception.SofaRpcException: Send message to remote catch error: HTTP 302 Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:189)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:150)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy90.https(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.rpc.transport.AbstractProxyClientTransport.doInvokeSync(AbstractProxyClientTransport.java:200)
	at com.alipay.sofa.rpc.transport.AbstractProxyClientTransport.syncSend(AbstractProxyClientTransport.java:162)
	at com.alipay.sofa.rpc.client.AbstractCluster.doSendMsg(AbstractCluster.java:514)
	at com.alipay.sofa.rpc.client.AbstractCluster.sendMsg(AbstractCluster.java:485)
	at com.alipay.sofa.rpc.filter.ConsumerInvoker.invoke(ConsumerInvoker.java:60)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:98)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:98)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:98)
	at com.alipay.sofa.rpc.filter.RpcReferenceContextFilter.invoke(RpcReferenceContextFilter.java:80)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:98)
	at com.alipay.sofa.rpc.filter.ConsumerExceptionFilter.invoke(ConsumerExceptionFilter.java:37)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:98)
	at com.alipay.sofa.rpc.filter.FilterChain.invoke(FilterChain.java:262)
	at com.alipay.sofa.rpc.client.AbstractCluster.filterChain(AbstractCluster.java:478)
	at com.alipay.sofa.rpc.client.FailoverCluster.doInvoke(FailoverCluster.java:66)
	at com.alipay.sofa.rpc.client.AbstractCluster.invoke(AbstractCluster.java:285)
	at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.rpc.filter.ProviderInvoker.invoke(ProviderInvoker.java:99)
	at com..framework.microservice.starter.sofa.log.filter.SofaServerLogFilter.invoke(SofaServerLogFilter.java:28)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:98)
	at com..framework.microservice.starter.sofa.access.filter.AccessControlFilter.invoke(AccessControlFilter.java:37)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:98)
	at com.sofa.rpc.filter.jaegertracer.ProviderTracerJaegerFilter.invoke(ProviderTracerJaegerFilter.java:70)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:98)
	at com.alipay.sofa.rpc.filter.ProviderBaggageFilter.invoke(ProviderBaggageFilter.java:45)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:98)
	at com.alipay.sofa.rpc.filter.RpcServiceContextFilter.invoke(RpcServiceContextFilter.java:62)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:98)
	at com.alipay.sofa.rpc.filter.ProviderExceptionFilter.invoke(ProviderExceptionFilter.java:37)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:98)
	at com.alipay.sofa.rpc.filter.FilterChain.invoke(FilterChain.java:262)
	at com.alipay.sofa.rpc.server.ProviderProxyInvoker.invoke(ProviderProxyInvoker.java:65)

sofa boot version: 2.6.3

**Comment by mailfly** [comment]
any update?
