### ISSUE TITLE
Error NullPointerException occurred when call service from one biz to another

### ISSUE THREAD

**Issue by ggndnn** [sofastack/sofa-boot#479]
Based on sofa-boot(v3.2.0) and sofa-ark(v1.0.0), when one biz tried to call a service from another biz, got a error:
```
java.lang.NullPointerException: null
    at com.alipay.sofa.runtime.invoke.DynamicJvmServiceProxyFinder.getBiz(DynamicJvmServiceProxyFinder.java:149) ~[runtime-sofa-boot-3.2.0.jar:na]
    at com.alipay.sofa.runtime.invoke.DynamicJvmServiceProxyFinder.findServiceProxy(DynamicJvmServiceProxyFinder.java:79) ~[runtime-sofa-boot-3.2.0.jar:na]
    at com.alipay.sofa.runtime.service.binding.JvmBindingAdapter$JvmServiceInvoker.doInvoke(JvmBindingAdapter.java:168) ~[runtime-sofa-boot-3.2.0.jar:na]
    at com.alipay.sofa.runtime.spi.service.ServiceProxy.invoke(ServiceProxy.java:40) ~[runtime-sofa-boot-3.2.0.jar:na]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.8.RELEASE.jar:5.1.8.RELEASE]
...
```

After analysis, I found this is caused by that `com.alipay.sofa.runtime.invoke.DynamicJvmServiceProxyFinder` was not exported by runtime-sofa-boot-plugin. The bizManagerService in `DynamicJvmServiceProxyFinder` loaded by bizClassLoaded did not have a chance to be injected.

Sofa-boot v3.1.5 did not have such issue, because runtime-sofa-boot-plugin exported package `com.alipay.sofa.runtime.integration` where `DynamicJvmServiceProxyFinder` was inside then.

`SofaEventHandler` is the same as `DynamicJvmServiceProxyFinder`, different from v3.1.5. And dependency hessian should be added to runtime-sofa-boot-plugin too.

I think the big reform of code organization in sofa-boot v3.2.0 brought some impact on sofa-ark at least.

**Comment by glmapper** [comment]
can you peovide a simple demo to show this bug？

**Comment by ggndnn** [comment]
Demo: [https://github.com/ggndnn/sofa-ark-samples/tree/demo](https://github.com/ggndnn/sofa-ark-samples/tree/demo)
Branch demo
Access http://localhost:8080/sample2/hello

**Comment by glmapper** [comment]
@ggndnn just upgrade SOFABoot version to 3.2.1-SNAPSHOT and upgrade the SOFAArk version to 1.1.0-SNAPSHOT. if there any other problem, you can reopen this issue again.
