### ISSUE TITLE
MultiApplicationHealthIndicator will trigger stackoverflow during health check

### ISSUE THREAD

**Issue by zhboseu** [sofastack/sofa-boot#583]
sofaboot 3.2.0+，引入sofa-ark
`java.util.ConcurrentModificationException: null
	at java.util.ArrayList.sort(ArrayList.java:1464) ~[?:1.8.0_231]
	at java.util.Collections.sort(Collections.java:143) ~[?:1.8.0_231]
	at com.alipay.sofa.isle.ApplicationRuntimeModel.getAllInactiveDeployments(ApplicationRuntimeModel.java:79) ~[isle-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.healthcheck.impl.ModuleHealthChecker.isHealthy(ModuleHealthChecker.java:67) ~[healthcheck-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.boot.actuator.health.SofaModuleHealthIndicator.health(SofaModuleHealthIndicator.java:37) ~[sofa-boot-actuator-3.2.1.jar:3.2.1]
	at com.alipay.sofa.healthcheck.impl.SofaRuntimeHealthChecker.isLivenessHealth(SofaRuntimeHealthChecker.java:52) ~[healthcheck-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.isLivenessHealth(StandardSofaRuntimeManager.java:78) ~[runtime-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.boot.actuator.health.MultiApplicationHealthIndicator.health(MultiApplicationHealthIndicator.java:38) ~[sofa-boot-actuator-3.2.1.jar:3.2.1]
	at com.alipay.sofa.healthcheck.impl.SofaRuntimeHealthChecker.isLivenessHealth(SofaRuntimeHealthChecker.java:52) ~[healthcheck-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.isLivenessHealth(StandardSofaRuntimeManager.java:78) ~[runtime-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.boot.actuator.health.MultiApplicationHealthIndicator.health(MultiApplicationHealthIndicator.java:38) ~[sofa-boot-actuator-3.2.1.jar:3.2.1]
	at com.alipay.sofa.healthcheck.impl.SofaRuntimeHealthChecker.isLivenessHealth(SofaRuntimeHealthChecker.java:52) ~[healthcheck-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.isLivenessHealth(StandardSofaRuntimeManager.java:78) ~[runtime-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.boot.actuator.health.MultiApplicationHealthIndicator.health(MultiApplicationHealthIndicator.java:38) ~[sofa-boot-actuator-3.2.1.jar:3.2.1]
	at com.alipay.sofa.healthcheck.impl.SofaRuntimeHealthChecker.isLivenessHealth(SofaRuntimeHealthChecker.java:52) ~[healthcheck-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.isLivenessHealth(StandardSofaRuntimeManager.java:78) ~[runtime-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.boot.actuator.health.MultiApplicationHealthIndicator.health(MultiApplicationHealthIndicator.java:38) ~[sofa-boot-actuator-3.2.1.jar:3.2.1]
	at com.alipay.sofa.healthcheck.impl.SofaRuntimeHealthChecker.isLivenessHealth(SofaRuntimeHealthChecker.java:52) ~[healthcheck-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.isLivenessHealth(StandardSofaRuntimeManager.java:78) ~[runtime-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.boot.actuator.health.MultiApplicationHealthIndicator.health(MultiApplicationHealthIndicator.java:38) ~[sofa-boot-actuator-3.2.1.jar:3.2.1]
	at com.alipay.sofa.healthcheck.impl.SofaRuntimeHealthChecker.isLivenessHealth(SofaRuntimeHealthChecker.java:52) ~[healthcheck-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.isLivenessHealth(StandardSofaRuntimeManager.java:78) ~[runtime-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.boot.actuator.health.MultiApplicationHealthIndicator.health(MultiApplicationHealthIndicator.java:38) ~[sofa-boot-actuator-3.2.1.jar:3.2.1]
	at com.alipay.sofa.healthcheck.impl.SofaRuntimeHealthChecker.isLivenessHealth(SofaRuntimeHealthChecker.java:52) ~[healthcheck-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.isLivenessHealth(StandardSofaRuntimeManager.java:78) ~[runtime-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.boot.actuator.health.MultiApplicationHealthIndicator.health(MultiApplicationHealthIndicator.java:38) ~[sofa-boot-actuator-3.2.1.jar:3.2.1]
	at com.alipay.sofa.healthcheck.impl.SofaRuntimeHealthChecker.isLivenessHealth(SofaRuntimeHealthChecker.java:52) ~[healthcheck-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.isLivenessHealth(StandardSofaRuntimeManager.java:78) ~[runtime-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.boot.actuator.health.MultiApplicationHealthIndicator.health(MultiApplicationHealthIndicator.java:38) ~[sofa-boot-actuator-3.2.1.jar:3.2.1]
	at com.alipay.sofa.healthcheck.impl.SofaRuntimeHealthChecker.isLivenessHealth(SofaRuntimeHealthChecker.java:52) ~[healthcheck-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.isLivenessHealth(StandardSofaRuntimeManager.java:78) ~[runtime-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.boot.actuator.health.MultiApplicationHealthIndicator.health(MultiApplicationHealthIndicator.java:38) ~[sofa-boot-actuator-3.2.1.jar:3.2.1]
	at com.alipay.sofa.healthcheck.impl.SofaRuntimeHealthChecker.isLivenessHealth(SofaRuntimeHealthChecker.java:52) ~[healthcheck-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.runtime.component.impl.StandardSofaRuntimeManager.isLivenessHealth(StandardSofaRuntimeManager.java:78) ~[runtime-sofa-boot-3.2.1.jar:3.2.1]
	at com.alipay.sofa.boot.actuator.health.MultiApplicationHealthIndicator.health(MultiApplicationHealthIndicator.java:38) ~[sofa-boot-actuator-3.2.1.jar:3.2.1]`

**Comment by alaneuler** [comment]
Method `health()` of MultiApplicationHealthIndicator will result in infinity recursive Spring indicator invoke.

SofaRuntimeHealthChecker contains MultiApplicationHealthIndicator:
![image](https://user-images.githubusercontent.com/8054939/72325743-be39e800-36e8-11ea-9711-4f19a34f0362.png)
