### ISSUE TITLE
runtime-sofa-boot-plugin v3.2.2 updated to v3.3.0 or above throws an exception

### ISSUE THREAD

**Issue by 343585776** [sofastack/sofa-boot#614]
**更新sofaboot版本至3.3.0或3.3.1,使用动态模块能力jvm通信时候加入的runtime-sofa-boot-plugin会抛出如下异常:**

`Exception in thread "main" java.lang.RuntimeException: Meet exception when determine whether to start SOFAArk!
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:49)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:30)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:70)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:47)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at me.sdevil507.MasterContainerApplication.main(MasterContainerApplication.java:15)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:59)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.startUpArk(ArkApplicationStartListener.java:55)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:41)
	... 11 more
Caused by: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.thread.IsolatedThreadGroup.rethrowUncaughtException(IsolatedThreadGroup.java:50)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:55)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.support.thread.LaunchRunner.run(LaunchRunner.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:68)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:77)
	... 6 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.reflect.InvocationTargetException
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:81)
	at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:143)
	at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:104)
	... 14 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.reflect.InvocationTargetException
	at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:56)
	at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55)
	at com.alipay.sofa.ark.container.pipeline.DeployBizStage.process(DeployBizStage.java:46)
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75)
	... 16 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:228)
	at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:52)
	... 19 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'runtimeContextBeanFactoryPostProcessor' defined in class path resource [com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.class]: Unsatisfied dependency expressed through method 'runtimeContextBeanFactoryPostProcessor' parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sofaRuntimeContext' defined in class path resource [com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sofaRuntimeContext' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sofaRuntimeManager' defined in class path resource [com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.runtime.spi.component.SofaRuntimeManager]: Factory method 'sofaRuntimeManager' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextAware
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1320)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1159)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:179)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at me.sdevil507.MasterContainerApplication.main(MasterContainerApplication.java:15)
	... 26 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sofaRuntimeContext' defined in class path resource [com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sofaRuntimeContext' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sofaRuntimeManager' defined in class path resource [com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.runtime.spi.component.SofaRuntimeManager]: Factory method 'sofaRuntimeManager' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextAware
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1320)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1159)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1255)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 45 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sofaRuntimeManager' defined in class path resource [com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.runtime.spi.component.SofaRuntimeManager]: Factory method 'sofaRuntimeManager' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextAware
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1320)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1159)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1255)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 59 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.runtime.spi.component.SofaRuntimeManager]: Factory method 'sofaRuntimeManager' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextAware
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 73 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextAware
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.resolveLocalClass(AbstractClasspathClassLoader.java:298)
	at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadClassInternal(PluginClassLoader.java:97)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.resolveExportClass(AbstractClasspathClassLoader.java:259)
	at com.alipay.sofa.ark.container.service.classloader.BizClassLoader.loadClassInternal(BizClassLoader.java:88)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.alipay.sofa.boot.autoconfigure.runtime.SofaRuntimeAutoConfiguration.sofaRuntimeManager(SofaRuntimeAutoConfiguration.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 74 more
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: [ArkPlugin Loader] runtime-sofa-boot-plugin : can not load class: org.springframework.context.ApplicationContextAware
	at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadClassInternal(PluginClassLoader.java:117)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 98 more`

需要显式指定runtime-sofa-boot-plugin版本为3.2.2或以下才能正常运行。

**Comment by SnapDL** [comment]
我也遇到类似的问题，升级到sofaboot3.3.1之后，业务ark-biz模块启动报runtime-sofa-ark-plugin依赖的错误，按你说的指定runtime-sofa-ark-plugin版本为3.2.2之后启动正常了

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sofaRuntimeManager' defined in class path resource [com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.runtime.spi.component.SofaRuntimeManager]: Factory method 'sofaRuntimeManager' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextAware
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1320)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1159)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1255)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
        ... 53 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alipay.sofa.runtime.spi.component.SofaRuntimeManager]: Factory method 'sofaRuntimeManager' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextAware
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
        ... 67 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextAware
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.resolveLocalClass(AbstractClasspathClassLoader.java:298)
        at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadClassInternal(PluginClassLoader.java:97)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:67)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.resolveExportClass(AbstractClasspathClassLoader.java:259)
        at com.alipay.sofa.ark.container.service.classloader.BizClassLoader.loadClassInternal(BizClassLoader.java:88)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:67)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.alipay.sofa.boot.autoconfigure.runtime.SofaRuntimeAutoConfiguration.sofaRuntimeManager(SofaRuntimeAutoConfiguration.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 68 more
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: [ArkPlugin Loader] runtime-sofa-boot-plugin : can not load class: org.springframework.context.ApplicationContextAware
        at com.alipay.sofa.ark.container.service.classloader.PluginClassLoader.loadClassInternal(PluginClassLoader.java:117)
        at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:67)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 92 more
Exception in thread "Thread-0" com.alipay.sofa.ark.exception.ArkRuntimeException: java.lang.RuntimeException: No SofaRuntimeManager Found!
        at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.unDeploy(DefaultBizDeployer.java:70)
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.unDeploy(BizDeployServiceImpl.java:62)
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.dispose(BizDeployServiceImpl.java:73)
        at com.alipay.sofa.ark.container.service.ArkServiceContainer.stop(ArkServiceContainer.java:144)
        at com.alipay.sofa.ark.container.ArkContainer.stop(ArkContainer.java:242)
        at com.alipay.sofa.ark.container.ArkContainer$1.run(ArkContainer.java:136)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No SofaRuntimeManager Found!
        at com.alipay.sofa.runtime.SofaBizUninstallEventHandler.getSofaRuntimeManager(SofaBizUninstallEventHandler.java:49)
        at com.alipay.sofa.runtime.SofaBizUninstallEventHandler.doUninstallBiz(SofaBizUninstallEventHandler.java:38)
        at com.alipay.sofa.runtime.SofaBizUninstallEventHandler.handleEvent(SofaBizUninstallEventHandler.java:33)
        at com.alipay.sofa.runtime.SofaBizUninstallEventHandler.handleEvent(SofaBizUninstallEventHandler.java:29)
        at com.alipay.sofa.ark.container.service.event.EventAdminServiceImpl.sendEvent(EventAdminServiceImpl.java:74)
        at com.alipay.sofa.ark.container.model.BizModel.stop(BizModel.java:256)
        at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.unDeploy(DefaultBizDeployer.java:66)

**Comment by jinkunaier** [comment]
同问，在几个地方都提出这个问题了，一直没人能解答！

**Comment by alaneuler** [comment]
这个问题是从 3.3.0 引入的，sofaboot 本身使用了 spring 中的类

**Comment by glmapper** [comment]
@jinkunaier @SnapDL @343585776 3.3.0 版本中由于 sofaboot 部分类直接使用了 spring 相关的类，导致插件在启动时会有问题；目前有两种解决方案：1、参考 http://www.glmapper.com/2020/04/03/solution-series-dynamic-module/   2、通过自定义插件将 spring 相关类全部打在 plugin 中

**Comment by jinkunaier** [comment]
@SnapDL @343585776 https://github.com/jinkunaier/ark-multi-web   这个是我整合的一个demo，在钉钉群里面大佬的指导下，我把官方的runtime-sofa-boot-plugin弄到本地，加了个spring的依赖，就可以了。具体有没有其它问题还没发现，你们可以参考一下。
