### ISSUE TITLE
从3.15升级到 3.4.6启动失败

### ISSUE THREAD

**Issue by opjk** [sofastack/sofa-boot#769]
**报错**
java.lang.NoClassDefFoundError: com/alipay/sofa/infra/log/space/SofaBootLogSpaceIsolationInit
	at com.alipay.sofa.rpc.boot.SofaBootRpcInitializer.initStarterLog(SofaBootRpcInitializer.java:65)
	at com.alipay.sofa.rpc.boot.SofaBootRpcInitializer.initialize(SofaBootRpcInitializer.java:44)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:635)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:390)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	at com.gridnt.AppServerStarter.main(AppServerStarter.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.ClassNotFoundException: com.alipay.sofa.infra.log.space.SofaBootLogSpaceIsolationInit
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 11 common frames omitted

**依赖配置**
compile "com.alipay.sofa:sofaboot-dependencies:3.4.6"
compile group: "com.alipay.sofa", name: "runtime-sofa-boot-starter", version: "3.4.6"
compile group: "com.alipay.sofa", name: "infra-sofa-boot-starter", version: "3.4.6"
group: "com.alipay.sofa", name: "rpc-sofa-boot-starter", version: "6.0.4" 

**查看了一下**
rpc-sofa-boot-starter  6.0.4 中调用类 SofaBootLogSpaceIsolationInit  3.4.6中没有，

如果处理呢？

**Comment by ujjboy** [comment]
rpc-sofa-boot-starter 不建议单独引版本

**Comment by opjk** [comment]
> rpc-sofa-boot-starter 不建议单独引版本

谢谢，但是不引用，又缺少依赖呢，能给个依赖配置参考一下么？

**Comment by alaneuler** [comment]
starter 里面包含了完整的依赖的，把你的 gradle 配置发下呢

**Comment by opjk** [comment]
> starter 里面包含了完整的依赖的，把你的 gradle 配置发下呢

**启动正常的配置**
ext {
   springBoot="2.4.0"
   **sofaVersion = "3.1.5"**
    mybatisPlus = "3.4.1"
    druidVersion = "1.2.3"
}
dependencies {
    compile "org.springframework.boot:spring-boot-starter:${springBoot}"
    compile "com.alipay.sofa:runtime-sofa-boot-starter:${sofaVersion}"
    compile "com.alipay.sofa:infra-sofa-boot-starter:${sofaVersion}"
    compile("com.alipay.sofa:rpc-sofa-boot-starter:6.0.4") {
    }
    compile "com.baomidou:mybatis-plus-annotation:${mybatisPlus}"
    compile "com.baomidou:mybatis-plus-extension:${mybatisPlus}"
    compile "com.google.guava:guava:30.0-jre"
    compile "com.alibaba:fastjson:1.2.75"
    implementation "org.mariadb.jdbc:mariadb-java-client:2.7.1"
    implementation "org.springframework.boot:spring-boot-starter-data-redis:${springBoot}"
    implementation "com.fasterxml.jackson.core:jackson-databind:2.12.0"
}

**升级到 3.4.6启动失败**  提示 找不到类报上面的错误。
 sofaVersion = "3.4.6"

`java.lang.NoClassDefFoundError: com/alipay/sofa/infra/log/space/SofaBootLogSpaceIsolationInit`

rpc-sofa-boot-starter 6.0.4 中调用类 SofaBootLogSpaceIsolationInit  在 infra-sofa-boot-starter 的 3.4.6版本中没有。

如果升级，依赖的jar包是不是要换一下呢？谢谢！

**Comment by alaneuler** [comment]
建议参照 Spring Boot 官方的 build.gradle 的 demo，不用自己指定版本，而是使用 plugin 机制，sofa-boot-gradle-plugin；
这样就不会出现版本升级出现不兼容的情况。
