### ISSUE TITLE
引入healthcheck之后应用启动报错

### ISSUE THREAD

**Issue by wangchen111** [sofastack/sofa-boot#797]
工程由springboot改为sofaboot，并且引入healthcheck-sofa-boot-starter。启动应用出现错误，但启动后访问/actuator/readiness可以获取健康信息。
![image](https://user-images.githubusercontent.com/11702955/103873092-41c6c300-510a-11eb-959c-de45f13172f3.png)

**Comment by wangchen111** [comment]
错误信息如下：
2021-01-07 16:33:37.311  WARN 10772 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : Exception from healthcheckHandler.getStatus, setting status to DOWN

java.lang.IllegalArgumentException: App is still in startup process, please try later!
	at org.springframework.util.Assert.isTrue(Assert.java:118)
	at com.alipay.sofa.boot.actuator.health.SofaBootHealthIndicator.health(SofaBootHealthIndicator.java:51)
	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:95)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:110)
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:106)
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1388)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2021-01-07 16:33:37.311  WARN 10772 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1610008417311, current=DOWN, previous=UP]
2021-01-07 16:33:37.311  WARN 10772 --- [nfoReplicator-0] c.n.discovery.InstanceInfoReplicator     : Ignoring onDemand update due to rate limiter

**Comment by alaneuler** [comment]
这个只是在**启动期**的时候有个外部请求触发了 spring boot 的 health indicator 的逻辑，SOFABoot 检查到应用没有启动完成，然后出现了上述错误，这个错误不影响启动。
