### ISSUE TITLE
Process pipeline stage fail: com.alipay.sofa.ark.container.pipeline.HandleArchiveStage

### ISSUE THREAD

**Issue by LeoDominicXu** [sofastack/sofa-boot#826]
2021-04-27 17:29:06,375 INFO  main                             - Begin to start ArkServiceContainer
2021-04-27 17:29:06,917 INFO  main                             - Init Service: com.alipay.sofa.ark.container.session.StandardTelnetServerImpl
2021-04-27 17:29:06,917 INFO  main                             - Listening on port: 1234
2021-04-27 17:29:07,192 INFO  main                             - Init Service: com.alipay.sofa.ark.container.service.plugin.PluginDeployServiceImpl
2021-04-27 17:29:07,192 INFO  main                             - Init Service: com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl
2021-04-27 17:29:07,192 INFO  main                             - Init Service: com.alipay.sofa.ark.container.service.classloader.ClassLoaderServiceImpl
2021-04-27 17:29:07,200 INFO  main                             - Finish to start ArkServiceContainer
2021-04-27 17:29:07,217 INFO  main                             - Start to process pipeline stage: com.alipay.sofa.ark.container.pipeline.HandleArchiveStage
2021-04-27 17:29:07,323 ERROR main                             - Process pipeline stage fail: com.alipay.sofa.ark.container.pipeline.HandleArchiveStage
com.alipay.sofa.ark.exception.ArkRuntimeException: null
	at com.alipay.sofa.ark.container.pipeline.HandleArchiveStage.process(HandleArchiveStage.java:167)
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75)
	at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:143)
	at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:68)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.support.thread.LaunchRunner.run(LaunchRunner.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at com.alipay.sofa.ark.container.pipeline.HandleArchiveStage.process(HandleArchiveStage.java:147)
	... 17 common frames omitted
2021-04-27 17:29:07,333 INFO  Thread-1                         - Begin to stop ArkServiceContainer
2021-04-27 17:29:07,333 INFO  Thread-1                         - Dispose service: com.alipay.sofa.ark.container.service.classloader.ClassLoaderServiceImpl
2021-04-27 17:29:07,333 INFO  Thread-1                         - Dispose service: com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl
2021-04-27 17:29:07,333 INFO  Thread-1                         - Dispose service: com.alipay.sofa.ark.container.service.plugin.PluginDeployServiceImpl
2021-04-27 17:29:07,333 INFO  Thread-1                         - Dispose service: com.alipay.sofa.ark.container.session.StandardTelnetServerImpl
2021-04-27 17:29:07,336 INFO  Thread-1                         - Finish to stop ArkServiceContainer

**Comment by LeoDominicXu** [comment]
报空指针，但去掉非宿主biz是可以启动的。

**Comment by glmapper** [comment]
> 报空指针，但去掉非宿主biz是可以启动的。

Maybe your normal biz is illegal
